version = 1

[[annotations]]
path = [
    ".gitignore",
    "Makefile",
    "CONTRIBUTING.md",
    "README.md",
    "Resources/AppIcon.icns",
    "Resources/Info.plist",
    "docs/images/*.png",
]
SPDX-FileCopyrightText = "Copyright James Martin and DS Menu Bar contributors"
SPDX-License-Identifier = "MIT"
